# SPDX-License-Identifier: GPL-2.0
#
# Makefile for livepatch callback test code.

obj-$(CONFIG_TEST_LIVEPATCH) += \
	test_klp_callbacks_demo.o \
	test_klp_callbacks_demo__test_klp_busy_module.o \
	test_klp_callbacks_demo__test_klp_module.o \
	test_klp_callbacks_demo2.o \
