# SPDX-License-Identifier: GPL-2.0

TEST_PROGS_EXTENDED := functions.sh
TEST_PROGS := \
	test-basic.sh \
	test-callbacks.sh \
	test-ftrace.sh \
	test-klp-convert.sh \
	test-shadow-vars.sh \
	test-state.sh 

include ../lib.mk
